name: build-android-and-web

on:
  push:
    branches: [ master, main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          channel: 'stable'

      - name: Flutter pub get
        run: flutter pub get

      - name: Build Android APK (release)
        run: flutter build apk --release --dart-define=CI=true

      - name: Build Web (release)
        run: flutter build web --release --dart-define=CI=true

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload Web build artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web

      # 可选：上传到 Appetize 以在浏览器中交互预览（需要设置 APPETIZE_TOKEN 机密）
      # - name: Upload to Appetize (optional)
      #   if: ${{ secrets.APPETIZE_TOKEN != '' }}
      #   run: |
      #     curl https://$APPETIZE_TOKEN@api.appetize.io/v1/apps \
      #       -F platform=android \
      #       -F file=@build/app/outputs/flutter-apk/app-release.apk \
      #       -F note="ShopLite nightly"
      #   env:
      #     APPETIZE_TOKEN: ${{ secrets.APPETIZE_TOKEN }}


