name: build-android-and-web
on:
  workflow_dispatch:
  push:
    branches: [ master, main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          channel: 'stable'

      - name: Cache pub packages
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: pub-${{ runner.os }}-${{ hashFiles('**/pubspec.lock') }}

      - name: Flutter doctor (verbose)
        run: flutter doctor -v

      - name: Accept Android licenses
        run: yes | flutter doctor --android-licenses || true

      - name: Pub get (verbose)
        run: flutter pub get -v

      - name: Build Android APK (verbose)
        run: flutter build apk -v --release --dart-define=CI=true || (sudo apt-get update && sudo apt-get install -y libstdc++6 && flutter build apk -v --release --dart-define=CI=true)

      - name: Build Web (release)
        run: flutter build web --release --dart-define=CI=true

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7

      - name: Upload Web build artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web
          retention-days: 7
